/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/tetris_test.check" instead.
 */

#include <check.h>

#line 1 "tests/tetris_test.check"
#include <check.h>
#include "../brick_game/brickgame.h"

START_TEST(initialization)
{
#line 5
  GameInfo_t info = updateCurrentState();
  Figure_t *figure = figure_init();
  ck_assert_int_eq(info.level, 1);
  ck_assert_int_eq(info.score, 0);
  ck_assert_int_eq(info.speed, 800000);
  ck_assert_int_eq(info.pause, 1);
  ck_assert_int_eq(info.high_score, 0);
  ck_assert_int_eq(figure->x, 5);
  ck_assert_int_eq(figure->y, 2);

}
END_TEST

START_TEST(movement)
{
#line 16
  Figure_t *figure = figure_init();
  move_left();
  ck_assert_int_eq(figure->x, 4);
  move_right();
  ck_assert_int_eq(figure->x, 5);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, initialization);
    tcase_add_test(tc1_1, movement);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
